BB_CONF_FRAGMENT_SUMMARY = "Enable CRA webinar features"
BB_CONF_FRAGMENT_DESCRIPTION = "Enable CRA webinar features"

INHERIT += "cve-check"
include cve-extra-exclusions.inc

DISTRO_FEATURES:remove = "sysvinit"
# Enable AppArmor in the distribution
DISTRO_FEATURES:append = " apparmor systemd usrmerge"

# 2. Use systemd as the init manager
VIRTUAL-RUNTIME_init_manager = "systemd"

# Ensure the kernel includes AppArmor features
KERNEL_FEATURES:append = " features/apparmor/apparmor.scc"

# Install AppArmor tools, Python, and our custom vulnerable app
IMAGE_INSTALL:append = " apparmor python3-core python3-netserver vuln-server"

IMAGE_FEATURES += "allow-empty-password allow-root-login empty-root-password post-install-logging"

